### ISSUE TITLE
Add unique_subject = no to config file created by openssl::csr

### ISSUE THREAD

**Issue by damonmaria** [smoeding/puppet-openssl#6]
At the moment, you can't re-create a certificate from the csr and config generated by `openssl::csr` because the default is to disallow multiple certs with the same subject name. 

The [openssl manual](https://www.openssl.org/docs/man1.1.1/man1/openssl-ca.html) says this is for backwards compatibility and it's recommended to set `unique_subject = no`. 

Can this be done in `csr.conf.epp`?

**Comment by smoeding** [comment]
The `unique_subject` setting must be set in the config file of the CA that is used to sign the CSR. It is the CA that keeps a record of the certificates it has issued and therefore it is only useful in the context of the CA.

**Comment by damonmaria** [comment]
Hmmm... that's what I had expected and had already tried that in my `ca.cnf` passed into `openssl_signcsr`, but it seemed to have no effect. So I assumed it was expected from the config created with the CSR. 

Here's my `ca.cnf`. Many of these values are mandatory so this file is getting used:
```
[ my-ca ]
certificate    = /etc/etcd/ca.pem
private_key    = /etc/etcd/ca/ca-key.pem

new_certs_dir  = /etc/etcd/ca
database       = /etc/etcd/ca/index.txt
serial         = /etc/etcd/ca/serial.txt
default_md     = sha256
policy         = policy_anything
unique_subject = no

[ policy_anything ]
countryName             = optional
stateOrProvinceName     = optional
localityName            = optional
organizationName        = optional
organizationalUnitName  = optional
commonName              = supplied
emailAddress            = optional
```

**Comment by smoeding** [comment]
You might be hitting the issue described at https://github.com/OpenVPN/easy-rsa/issues/40 and the linked text at https://pyro.eu.org/how-to/micro/openssl-txt_db-error-number-2.txt

It seems it might not work if you add the `unique_subject` config item after the cert database has been created.
Check the file named `/etc/etcd/ca/index.txt.attr` in your setup.

**Comment by damonmaria** [comment]
That was exactly the issue. Good catch. And thanks for the module. I couldn't find any other that signed certificates properly.
